// GENERAT per scripts/marques/retalla-logos.cjs. No s'edita a mà: torna a córrer l'script.
// Mida de la TINTA de cada logo (sense el marge blanc que portava el fitxer original).
export const MIDES_LOGOS: Record<string, { src: string; amplada: number; alcada: number }> = {
  "COUCKE.jpg": { src: "/images/brands/retallats/COUCKE.webp", amplada: 238, alcada: 115 },
  "Graccioza.png": { src: "/images/brands/retallats/Graccioza.webp", amplada: 311, alcada: 104 },
  "Linen-Silk.jpg": { src: "/images/brands/retallats/Linen-Silk.webp", amplada: 364, alcada: 59 },
  "Sorema.jpg": { src: "/images/brands/retallats/Sorema.webp", amplada: 400, alcada: 64 },
  "UNIVERSAL.png": { src: "/images/brands/retallats/UNIVERSAL.webp", amplada: 293, alcada: 174 },
  "VERTISOL.png": { src: "/images/brands/retallats/VERTISOL.webp", amplada: 559, alcada: 124 },
  "Visensible.png": { src: "/images/brands/retallats/Visensible.webp", amplada: 251, alcada: 79 },
  "WINKLER.jpg": { src: "/images/brands/retallats/WINKLER.webp", amplada: 276, alcada: 64 },
  "aldeco.jpg": { src: "/images/brands/retallats/aldeco.webp", amplada: 132, alcada: 89 },
  "armura.jpg": { src: "/images/brands/retallats/armura.webp", amplada: 222, alcada: 50 },
  "astral.png": { src: "/images/brands/retallats/astral.webp", amplada: 123, alcada: 92 },
  "bandalux.jpg": { src: "/images/brands/retallats/bandalux.webp", amplada: 280, alcada: 64 },
  "bassols.jpg": { src: "/images/brands/retallats/bassols.webp", amplada: 198, alcada: 58 },
  "designers_guild.jpg": { src: "/images/brands/retallats/designers_guild.webp", amplada: 314, alcada: 24 },
  "froca.jpg": { src: "/images/brands/retallats/froca.webp", amplada: 248, alcada: 45 },
  "kas.jpg": { src: "/images/brands/retallats/kas.webp", amplada: 167, alcada: 167 },
  "klinun.jpg": { src: "/images/brands/retallats/klinun.webp", amplada: 227, alcada: 139 },
  "ma-salgueiro.jpg": { src: "/images/brands/retallats/ma-salgueiro.webp", amplada: 133, alcada: 163 },
  "nici.png": { src: "/images/brands/retallats/nici.webp", amplada: 300, alcada: 109 },
  "pepa-pastor.jpg": { src: "/images/brands/retallats/pepa-pastor.webp", amplada: 265, alcada: 46 },
  "piubell.jpg": { src: "/images/brands/retallats/piubell.webp", amplada: 181, alcada: 174 },
  "romo.jpg": { src: "/images/brands/retallats/romo.webp", amplada: 266, alcada: 53 },
  "scenes.jpg": { src: "/images/brands/retallats/scenes.webp", amplada: 140, alcada: 82 },
  "velfont.jpg": { src: "/images/brands/retallats/velfont.webp", amplada: 269, alcada: 124 },
  "vivaraise.jpg": { src: "/images/brands/retallats/vivaraise.webp", amplada: 265, alcada: 44 },
  "yutes.jpg": { src: "/images/brands/retallats/yutes.webp", amplada: 164, alcada: 59 },
};
